### ISSUE TITLE
Star count

### ISSUE THREAD

**Issue by qrpike** [avelino/awesome-go#1266]
Would be amazing if next to the name it would have the stars the project has on github. Most important thing when looking through the list is how popular / active the project is.

**Comment by kirillDanshin** [comment]
@qrpike it's a bad idea because the stars on github isn't an reliable metric. the only reliable way to decide to use or not to use a package in your project - is to use your eyes and brain, but never watchers/stars/fork counts.

**Comment by qrpike** [comment]
Definitely, but if 4 of the libraries have 2 stars and one has 2000 stars, there is no question which one I am going with.

**Comment by joeybloggs** [comment]
And that's exactly why @qrpike this shouldn't be done `stars != good library`

And if everyone thought that way then new libraries, that may be fantastic, would never get any attention.

**Comment by qrpike** [comment]
Something on the 99th page of hacker news may be better than the #1 item, but the front page is a culmination of what other people think is good. Same goes for Reddit or any other social ranking system.

**Comment by joeybloggs** [comment]
This isn't social media and people need to use their own judgement on what works for them.

**Comment by qrpike** [comment]
I don't think HN is social media, its a community around tech/development. As is github. But I rest my case. Good project even without stars.

**Comment by kirillDanshin** [comment]
I'm with @joeybloggs. we already maintaining a list of awesome projects and we filter out and merge only the best projects and trying to help projects to become better. you even can see that after [this commit](https://github.com/avelino/awesome-go/commit/dc872fce15a085165b1b93f2a693af41f8ab09b3) the community does better software just because they see that it is a recognized standard for the entire community.
if you want bigger list with something like `ORDER BY stars` you can use https://golanglibs.com/, but never rely on projects you'll find there just because there are popular. if you want smaller list but just with thing you can rely on, read awesome-go. we have no plans to add stars to the list because it breaks the whole idea of the list.
