### ISSUE TITLE
To which category can I add a key-value store abstraction with many interface implementations?

### ISSUE THREAD

**Issue by philippgille** [avelino/awesome-go#2321]
Hi, I created https://github.com/philippgille/gokv, which consists of a simple key-value store interface and *many* interface implementations:

- Local in-memory: Go sync.Map, Go map, FreeCache, BigCache
- Embedded: bbolt, BadgerDB, LevelDB / goleveldb, Local files 
- Distributed store: Redis, Consul, etcd, Apache ZooKeeper
- Distributed cache: Memcached
- Cloud: Amazon DynamoDB, Amazon S3 (and S3-compatible services like Google Cloud Storage and self-hosted solutions like Minio), Azure Table Storage, Google Cloud Datastore, Alibaba Cloud Table Store
- SQL: MySQL, PostgreSQL
- NoSQL: MongoDB
- "NewSQL": CockroachDB
- Multi-model: Apache Ignite

The interface implementations are just wrappers though (except for the "local files" implementation), so maybe it doesn't fit the *Databases implemented in Go* section. And it's also different from all the repos listed in *Database tools*. Where do you think it fits best? Or do you think it doesn't fit at all?

**Comment by ceriath** [comment]
Thanks!
I love the idea of having an abstraction layer, so you can easily swap out the underlying database, so it defintely should be on this list!

However, i think it would mostly fit in the **Database Driver** category. The problem is, that it's sorted between Relational and NoSQL. I see multiple implementations, that support multiple backends tho, so i'll just introduce a new category for those.
