### ISSUE TITLE
GoReportCard is struggling with go 1.18 and golint

### ISSUE THREAD

**Issue by spekary** [avelino/awesome-go#4114]
GoReportCard's github is reporting the following:

Go 1.18 generics is not working in gofmt or golint

golint has been deprecated and is not likely to be fixed.

**Comment by spekary** [comment]
GoReportCard has removed golint from its list of tools. I have recommended to them that they use staticcheck instead.

So, at this point in time, we will not be able to evaluate code quality with a linter unless we run it ourselves.

**Comment by avelino** [comment]
Sorry for the delay in answering

As GoReportCard does not yet support Go 1.8 (generic), we will disregard this iteM from the checklist and validate the others

GoReportCard is an open source project and this issue was opened there, we can contribute to it https://github.com/gojp/goreportcard/issues/381


As a second step we need to have our tools to depend as little as possible on third-party services
