### ISSUE TITLE
Duplicates

### ISSUE THREAD

**Issue by anacrolix** [avelino/awesome-go#423]
The list is full of duplicates. The idea of a list of "best-in-class" package is great. It makes it easier to know where to start when looking for a package with the desired functionality. But there are for many packages, 2, 3, 4 or more that do the same thing.

**Comment by mholt** [comment]
Like...?

**Comment by shurcooL** [comment]
IMO the most useful packages are those that implement an existing spec. For example, if you need an image decoder for Targa (TGA) file format, you come here, you find it, and you can use it. Maybe this isn't a great example, because there is not a single TGA decoder package on the list. I know about https://github.com/ftrvxmtrx/tga, maybe it should be added.

I'd be surprised if many people actively seek other people's logging and utility packages.

My point is that, when used in this way, having as many packages as possible is okay. If you want a list that contains only "best-in-class" packages, that would be the standard Go library, otherwise such a list doesn't really exist.

**Comment by dukex** [comment]
Closing it, if @anacrolix want keep this discussion we can reopen
