### ISSUE TITLE
Can we adopt a new policy?

### ISSUE THREAD

**Issue by frederikhors** [avelino/awesome-go#4244]
I like your project very much.

However here are often added projects that last a day or have little value for Go users.

Rust chose a different policy:

https://github.com/rust-unofficial/awesome-rust/blob/master/CONTRIBUTING.md:

> If you want to add an entry to the README.md please consider this:
> 
> is the entry valuable to people trying to get things done in Rust?
> In order to make this objective, the entry needs to either have at least 50 stars on Github, 2000 downloads on crates.io, or an equivalent level of other popularity metrics (which should be specified in the PR). The maintainers of this repo are not responsible for making your project popular, only for making more people aware of those projects. We don't want to have to pick and choose favourites, and so are using metrics like this to make our lives easier as maintainers.

What do you think?

Can we adopt it too?

Please consider this. 🙏

Thanks. 😃

**Comment by a5r0n** [comment]
the buttom line is, when develeopr is looking on a long list of projects, without any sort of ranking he just lost in the ocean, and the list is useless.

when i go to web page with 10+ projects, i will defintly not going to check every single one of them.
we need some way to get any sense of success/popularity to get any value from awesome lists.
stars are fine, imports too, anything that can help us to decide what to check first.

**Comment by phanirithvij** [comment]
I am of the same opinion, this is like Yahoo curated page before the invention of a search engine like Google.

The sort/filter etc features are only possible in a website but not the readme file. I guess the website needs to be improved rather than show stars etc in the readme. So a daily cron job, GitHub action to fetch info and save in db and show it in site using js. (scoop search by rasa works this way)
________________________________
