### ISSUE TITLE
First comment action is not working

### ISSUE THREAD

**Issue by carlmjohnson** [avelino/awesome-go#4939]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

I opened a PR and the first comment action failed. See https://github.com/avelino/awesome-go/actions/runs/5617543194.

Seems like a regression of https://github.com/avelino/awesome-go/issues/4868.

**Comment by avelino** [comment]
@carlmjohnson Can you send a corrected contribution?

**Comment by carlmjohnson** [comment]
You mean open a new PR?

**Comment by carlmjohnson** [comment]
Failed again: https://github.com/avelino/awesome-go/actions/runs/5617685809/job/15222150529?pr=4940

**Comment by khanhtc1202** [comment]
The error looks like it is a problem with the auth, got the same error all the time

> RequestError [HttpError]: Resource not accessible by integration
    at /home/runner/work/_actions/peter-evans/create-or-update-comment/v3/dist/index.js:4694:21
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  status: 403,

Maybe it is caused by the GITHUB_TOKEN does not have enough permission to perform its action, could you recheck?
https://github.com/avelino/awesome-go/blob/main/.github/workflows/pull-request-first-comment.yaml#L14

ref: https://github.com/peter-evans/create-or-update-comment#action-inputs

**Comment by richardwilkes** [comment]
This issue has been around for several months now, despite this issue only being posted recently. Is anyone actually looking into it?

**Comment by regnull** [comment]
I added a possible fix to https://github.com/avelino/awesome-go/pull/4961, not sure how to test it without creating a new dummy PR, and I don't want to spam the repo.

**Comment by regnull** [comment]
> I added a possible fix to #4961, not sure how to test it without creating a new dummy PR, and I don't want to spam the repo.

Since the issue appears to be fixed, I've removed the fix from #4961.

**Comment by richardwilkes** [comment]
I don't see a way to get the PR to re-run the action that was failing due to an expired token. Does this mean we need to kill our PRs and re-submit them?

**Comment by Prastiwar** [comment]
@avelino I've provided a fix with all the explanation on this PR:
- https://github.com/avelino/awesome-go/pull/5033

In order to completely verify the fix without and have 100% confidence instead relying on GitHub information the PR should be either:
- recreated by you
- merged and new test one should be created
