### ISSUE TITLE
Add a new contribution rule: Restrict projects that are unused and are not unique from being submitted

### ISSUE THREAD

**Issue by yassinebenaid** [avelino/awesome-go#5470]
A lot of PRs are submitting new projects. And, in a lot of cases, they are just redundant packages that do something one or more popular projects are doing it years before.

An example would be packages for task management (cron implementations), reflection packages, config files loaders,  web frameworks, dependency injection and many more.

These are the top categories that receive the most of new projects. That is not a problem, until it is.

A lot of newly submitted packages are doing the exact same thing, may be some API differences but still have the same interface, the same functionality and for the same use case.

So my suggestion is to add a new contribution rules that  indicate:

1. Not to submit new projects that don't have any or very few active users (we can specify a minimum threshold of stars for example)
2. We may break rule number 1 if, the project is offering a unique functionality that none or only few actively maintained projects are offering.
3. We may break rules number 1 and 2, if the project is considered better that others in some way (performance, adds new functionalities others are missing, ... etc)

Of course we can break all above rules in very rare cases depending on situation. However, PRs that break above rules will be closed.

Any thoughts @avelino @phanirithvij

**Comment by yassinebenaid** [comment]
Regarding: #5469

**Comment by phanirithvij** [comment]
"not unique" is not something I can decide.
github stars can be botted and bought.

so the one suggestion I can think of is a minimum of 5 months since first commit.

**Comment by yassinebenaid** [comment]
Alright, I agree. I will create a PR adding this to `CONTRIBUTING.md` and request for review.

**Comment by ccoVeille** [comment]
From my perspective, it depends about what you want to achieve

- Having fewer projects submitted
- write rules that are somehow already applied
- being able to quote a reason when refusing a project
- avoid poor project to be merged even if they comply existing rules
- allow yourself to remove a project while adding a new one, if it is better.

If the idea is only the first one, I'm afraid it won't work. People don't read documentation. They always want to promote their tools, without knowing or even trying to know another exists and is very popular and used.

So if your will is to provide a guidance to maintainers, I'm ok. Otherwise, I'm afraid it might be useless.
