### ISSUE TITLE
Please, include the date you are adding a new project.

### ISSUE THREAD

**Issue by paparipote** [avelino/awesome-go#748]
It let us increase expectations, let us see the emergence of new go products and, in some way, the evolution and maturity of go projects.
Regards.

**Comment by shurcooL** [comment]
Not sure what you mean, can you elaborate?

Can git blame be used to achieve this?

**Comment by paparipote** [comment]
Let me explain. Frequently I see the list in Readme.md because, between other things, I am interested to know the most recent additions. For  knowing that, I usually read the History of the changes (github helps in that purpose), and I thought it would be a good idea to include in every product the date when the author included a new awsome Go Project, for example:
•playlyfe - The Playlyfe Rest API Go SDK (31-dec-2015)
•redis - Redis-protocol compatible TCP servers/services.(01-dec-2015)
... etc.
Now, If it is not possible, no problem; it is important to note that it is only a suggestion.
Many thanks for your kindly attention.
Regards.

**Comment by matrixik** [comment]
Maybe there could be some tool for that that could create adding history from git (and someone would need to create it) but I think adding dates into README is bad idea. This dates are meaningless especially as list all the time grow in size. Searching by them would be increasingly hard.

**Comment by pyros2097** [comment]
The problem is the readme is not ordered by date so it might still be useless as you have to search for the most recent dates. The best approach i can think of is you should see the comitt history but the commit title's should improve so that we should be able to directly go the to project links.. because even I do that sometimes... I read the history then i need to go the diff of that commit and then i get the link which can be a bit cumbersome. So for now i started watching this repo.

**Comment by hloeffler** [comment]
radical solution: 
move data into json, render subset of the data to README.md
also solves the sorting problems :)
