### ISSUE TITLE
Anchors for titles with spaces don't work on awesome-go.com website (they work okay in README.md on github).

### ISSUE THREAD

**Issue by Epse** [avelino/awesome-go#983]
In the web page version on http://awesome-go.com clicking the link labeled "actual middlewares" doesn't do anything. The ID doesn't seem to exist

**Comment by shurcooL** [comment]
Hi @Epse,

Thanks for reporting this. It's a bug.

However, it affects more than just that one section, it's anything that has a space.

It happens because there is currently a mismatch in how the header anchors are generated on the website and on the README when viewed on github. Notice that "Actual middlewares" link works in GitHub:

https://github.com/avelino/awesome-go/blob/master/README.md#actual-middlewares

We should fix this inconsistency and make the website work as well.

This issue will track that (I'm a little surprised we didn't already have one open; this is a known issue that was raised before IIRC).

**Comment by kirillDanshin** [comment]
yep, it has `id="actualmiddlewares"` instead of `id="actual-middlewares"`.
It's a bug in showdown.js that is obsolete (see `// Copyright (c) 2007 John Fraser.` in http://awesome-go.com/assets/showdown.js).
I think we need to use something more actual. We can upgrade to [markdown-js](https://github.com/evilstreak/markdown-js) for example. Any objections?
@shurcooL @avelino @matrixik FYI.

**Comment by shurcooL** [comment]
I don't know anything about JavaScript markdown libraries, so I can't offer many comments. But no objections from me, as long as it works and nothing is broken. :)

**Comment by kirillDanshin** [comment]
fixed in https://github.com/avelino/awesome-go/commit/9959a7befc5c6f034bac502ea54bba92ec882948
also I've update the design.
check it out @shurcooL @avelino @Epse

**Comment by avelino** [comment]
thanks @kirillDanshin 
What do you think of generating the HTML around build and automatically update the index.html in the branch "gh-pages"? So we will be indexed in Google and we can work on SEO.

**Comment by kirillDanshin** [comment]
@avelino 
I'm working on it
